scalar JSON

# There isn't really an advantage in making these JSON types
# The main rationale for doing this is that then the engine lib can be used
# in the client as well since it uses the actual ts type defs instead of the
# GraphQL ones

type Game {
  id: String!

  name: String!
  createdAt: String!
  currentTurnNumber: Int!

  players: JSON!
  map: JSON!
  mapLayout: JSON!
  state(full: Boolean): JSON!
  actions(full: Boolean): JSON!
  log(full: Boolean): [JSON]!

  isPlayer: Boolean!
  turnReady: Boolean!
}

type User {
  id: String!

  name: String!
  email: String!
  admin: Boolean
}

type Viewer {
  id: ID!

  user: User!

  games: [Game]!
  users(search: String): [User]!
}

type Query {
  viewer: Viewer!
  game(gameId: String!): Game
}

input CreateGameInput {
  name: String!

  players: [String]!
}

input SubmitActionsInput {
  gameId: String!

  actions: [JSON]!
}

input AdvanceTurnInput {
  gameId: String!
}

input SetTurnReadyInput {
  gameId: String!
  turnReady: Boolean!
}

type CreateGamePayload {
  viewer: Viewer
  gameId: String
}

type SubmitActionsPayload {
  game: Game
}

type AdvanceTurnPayload {
  game: Game
}

type SetTurnReadyPayload {
  game: Game
}

type Mutation {
  createGame(input: CreateGameInput!): CreateGamePayload
  submitActions(input: SubmitActionsInput!): SubmitActionsPayload
  advanceTurn(input: AdvanceTurnInput!): AdvanceTurnPayload
  setTurnReady(input: SetTurnReadyInput!): SetTurnReadyPayload
}

schema {
  query: Query
  mutation: Mutation
}
