import * as _ from 'lodash'

import { ArmoringType, IUnitType, UnitClass, zeroResources } from '../definitions'

// tslint:disable:max-line-length

const unitList: IUnitType[] = [
  { kind: 'unit', id: 'unit_spear', name: 'Spear', shootingSpeed: 400, accuracy: 55, evasion: 17, endurance: 900, firePower: 150, strategicCaliber: 300, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 20, foodConsumption: 2, cost: zeroResources({ gold: 150, iron: 20, darkMatter: 0 }), technologyRequirements: {}, productionTime: 1, description: 'TODO', buildingRequirements: { building_spaceYard1: true } },
  { kind: 'unit', id: 'unit_explorer', name: 'Explorer', shootingSpeed: 300, accuracy: 30, evasion: 18, endurance: 1200, firePower: 200, strategicCaliber: 500, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 30, foodConsumption: 2, cost: zeroResources({ gold: 250, iron: 25, darkMatter: 0 }), technologyRequirements: { tech_small_ships: true }, productionTime: 1, description: 'TODO', buildingRequirements: { building_spaceYard1: true } },
  { kind: 'unit', id: 'unit_crusader', name: 'Crusader', shootingSpeed: 500, accuracy: 70, evasion: 16, endurance: 1500, firePower: 300, strategicCaliber: 400, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 40, foodConsumption: 3, cost: zeroResources({ gold: 150, iron: 40, darkMatter: 0 }), technologyRequirements: { tech_small_ships: true, tech_anti_armor_laser: true }, productionTime: 1, description: 'TODO', buildingRequirements: { building_spaceYard1: true } },
  { kind: 'unit', id: 'unit_hawk', name: 'Hawk', shootingSpeed: 600, accuracy: 60, evasion: 19, endurance: 1500, firePower: 300, strategicCaliber: 400, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 4, gasConsumption: 30, foodConsumption: 3, cost: zeroResources({ gold: 200, iron: 30, darkMatter: 0 }), technologyRequirements: { tech_small_ships: true }, productionTime: 1, description: 'TODO', buildingRequirements: { building_spaceYard1: true } },
  { kind: 'unit', id: 'unit_vessel', name: 'Vessel', shootingSpeed: 500, accuracy: 70, evasion: 16, endurance: 3500, firePower: 600, strategicCaliber: 400, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 40, foodConsumption: 4, cost: zeroResources({ gold: 330, iron: 40, darkMatter: 0 }), technologyRequirements: { tech_medium_ships: true }, productionTime: 1, description: 'TODO', buildingRequirements: { building_spaceYard2: true } },
  { kind: 'unit', id: 'unit_storm', name: 'Storm', shootingSpeed: 500, accuracy: 90, evasion: 13, endurance: 4500, firePower: 750, strategicCaliber: 500, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 50, foodConsumption: 4, cost: zeroResources({ gold: 400, iron: 50, darkMatter: 0 }), technologyRequirements: { tech_medium_ships: true, tech_bombs: true }, productionTime: 2, description: 'TODO', buildingRequirements: { building_spaceYard2: true } },
  { kind: 'unit', id: 'unit_massive', name: 'Massive', shootingSpeed: 500, accuracy: 70, evasion: 15, endurance: 5000, firePower: 800, strategicCaliber: 500, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 50, foodConsumption: 4, cost: zeroResources({ gold: 400, iron: 55, darkMatter: 0 }), technologyRequirements: { tech_medium_ships: true, tech_anti_armor_laser: true }, productionTime: 2, description: 'TODO', buildingRequirements: { building_spaceYard2: true } },
  { kind: 'unit', id: 'unit_admiral', name: 'Admiral', shootingSpeed: 400, accuracy: 75, evasion: 13, endurance: 9000, firePower: 900, strategicCaliber: 500, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 50, foodConsumption: 5, cost: zeroResources({ gold: 600, iron: 60, darkMatter: 0 }), technologyRequirements: { tech_large_ships: true }, productionTime: 2, description: 'TODO', buildingRequirements: { building_spaceYard3: true } },
  { kind: 'unit', id: 'unit_tornado', name: 'Tornado', shootingSpeed: 400, accuracy: 95, evasion: 10, endurance: 11000, firePower: 1000, strategicCaliber: 600, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 60, foodConsumption: 6, cost: zeroResources({ gold: 700, iron: 65, darkMatter: 1 }), technologyRequirements: { tech_large_ships: true, tech_bombs: true }, productionTime: 2, description: 'TODO', buildingRequirements: { building_spaceYard3: true } },
  { kind: 'unit', id: 'unit_immortal', name: 'Immortal', shootingSpeed: 400, accuracy: 80, evasion: 12, endurance: 12000, firePower: 1100, strategicCaliber: 600, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 60, foodConsumption: 6, cost: zeroResources({ gold: 750, iron: 70, darkMatter: 1 }), technologyRequirements: { tech_large_ships: true, tech_anti_armor_laser: true }, productionTime: 2, description: 'TODO', buildingRequirements: { building_spaceYard3: true } },
  { kind: 'unit', id: 'unit_mothership', name: 'MotherShip', shootingSpeed: 400, accuracy: 100, evasion: 8, endurance: 20000, firePower: 2000, strategicCaliber: 700, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 2, gasConsumption: 80, foodConsumption: 9, cost: zeroResources({ gold: 1200, iron: 90, darkMatter: 2 }), technologyRequirements: { tech_huge_ships: true, tech_bombs: true }, productionTime: 3, description: 'TODO', buildingRequirements: { building_spaceYard4: true } },
  { kind: 'unit', id: 'unit_tank', name: 'Tank', shootingSpeed: 300, accuracy: 50, evasion: 10, endurance: 10000, firePower: 300, strategicCaliber: 800, armoringType: ArmoringType.BASIC, unitClass: UnitClass.NONE, speed: 3, gasConsumption: 60, foodConsumption: 15, cost: zeroResources({ gold: 500, iron: 80, darkMatter: 2 }), technologyRequirements: { tech_large_ships: true }, productionTime: 2, description: 'TODO', buildingRequirements: { building_spaceYard3: true } },
]

export default _.keyBy(unitList, 'id')
