export default class RandomNameGenerator {
  names = NAMES

  getRandom() {
    if (!this.names.length) {
      throw new Error('available names finished')
    }

    const randomIndex = Math.floor(Math.random() * this.names.length)
    return this.names.splice(randomIndex, 1)[0]
  }
}

const NAMES = [
  'Acisajor',
  'Acisalis',
  'Acisdam',
  'Aciseldia',
  'Aciseldreus',
  'Aciselium Beta',
  'Aciselru',
  'Aciselzar cluster',
  'Acisendia',
  'Acisenea e4',
  'Acisenlis delta',
  'Acisentea system',
  'Acisenulore',
  'Aciserty',
  'Acisgua thule',
  'Acisilon e3',
  'Acislis cluster',
  'Acisokon',
  'Acisroid',
  'Acissia',
  'Acistica',
  'Acisulia-USR',
  'Acisusnus',
  'Acodam e4',
  'Acodia Beta',
  'Acoea III',
  'Acoellore e4',
  'Acoenubel',
  'Acoenveon',
  'Acolon',
  'Aconova',
  'Aconova-prism',
  'Acooran',
  'Acosuk homeworld',
  'Acosuk-helix',
  'Acosuk-K2',
  'Acovania',
  'Acuadros e3',
  'Acuatica',
  'Acudam',
  'Acudros',
  'Acuenusuk',
  'Acuenutea',
  'Acuiroid',
  'Acuivania',
  'Aculiv Prime',
  'Aculore',
  'Acuoid III',
  'Acuoium e4',
  'Acuojor Prime',
  'Acuolon',
  'Acuria',
  'Acutica',
  'Acutos',
  'Acuudros',
  'Acuunus-RX',
  'Acuusea',
  'Acuuury',
  'Acuzar',
  'Adulelveon',
  'Adulenerth',
  'Adulennus',
  'Adulensuk',
  'Adulenulia',
  'Adulerth',
  'Adulgus',
  'Adulinova',
  'Adulium-RX',
  'Aduljor',
  'Adullax',
  'Adullon-prism',
  'Adullore III',
  'Adulobel',
  'Aduloid',
  'Adulovania',
  'Adulroid III',
  'Adultea',
  'Aduluserth',
  'Aduluzar III',
  'Aluabel',
  'Aluelzar-helix',
  'Aluenkon',
  'Aluenulore',
  'Aluenurind',
  'Aluenusuk homeworld',
  'Alugua',
  'Alugus',
  'Aluigua',
  'Aluium-helix',
  'Alulia',
  'Alulis void',
  'Aluliv',
  'Alunus',
  'Aluoru',
  'Aluran',
  'Aluria',
  'Alutea',
  'Alutos',
  'Alutos delta',
  'Aluubel',
  'Aluunova',
  'Aluzar',
  'Amutatos',
  'Amutelliv',
  'Amutenulon-helix',
  'Amutenuveon III',
  'Amutigus',
  'Amutjor',
  'Amutrad',
  'Amutrind',
  'Amuttea-K2',
  'Amuttea-RX',
  'Amuttede',
  'Amuttica',
  'Amuttos',
  'Amutubel',
  'Amutuerty',
  'Amutustede Sigma',
  'Amutzar',
  'Arsaliv Prime',
  'Arsdreus',
  'Arselnova',
  'Arselvania e3',
  'Arselzar delta',
  'Arsensia void',
  'Arsenubula Prime',
  'Arsenurad thule',
  'Arsiium',
  'Arsiketh',
  'Arsiran-RX',
  'Arsjor',
  'Arslax',
  'Arslia',
  'Arslon',
  'Arsnova',
  'Arsnova-USR',
  'Arsoid',
  'Arsoium void',
  'Arsoroid',
  'Arsroid',
  'Arsudia',
  'Arsuketh Prime',
  'Arsuoid',
  'Arsury',
  'Arsury-helix',
  'Arsusium-X',
  'Asdreus-USR',
  'Asenium',
  'Asenudreus',
  'Asenunova',
  'Asenusuk thule',
  'Asgus Prime',
  'Asnova',
  'Asorind',
  'Asran',
  'Asria',
  'Asru Ruins',
  'Astica',
  'Asutica',
  'Asuzar',
  'Avisaerth-prism',
  'Avisalia Beta',
  'Avisea',
  'Avisenketh',
  'Avisenudam Beta',
  'Aviserth',
  'Aviserty',
  'Avisgus',
  'Avisium',
  'Avislax',
  'Avisnova',
  'Avisoid',
  'Avisrad void',
  'Avisroid cluster',
  'Avisuliv',
  'Avisulon',
  'Avisusrad',
  'Avisusru',
  'Avisvania',
  'Bibula',
  'Bidia',
  'Bidros e4',
  'Biea delta',
  'Biellis',
  'Bieltica',
  'Biendreus',
  'Bienrad Prime',
  'Bigua',
  'Biiru',
  'Biketh',
  'Bilia system',
  'Binova',
  'Biru Ruins',
  'Bisuk',
  'Bisuk-USR',
  'Bitea',
  'Bitede',
  'Bitos',
  'Bitos thule',
  'Biudia',
  'Biugus 12',
  'Blabaerth system',
  'Blabalon e3',
  'Blabaria',
  'Blabelgua',
  'Blabelvania',
  'Blabenketh',
  'Blabenuzar',
  'Blabium Beta',
  'Blabium cluster',
  'Blablax',
  'Blabliv',
  'Blabnus',
  'Blaborad cluster',
  'Blabotos',
  'Blabran',
  'Blabria Prime',
  'Blabsia delta',
  'Blabtica',
  'Blabtica system',
  'Bliadros',
  'Blidam',
  'Bliensuk',
  'Blienugus',
  'Blienunova',
  'Blierty',
  'Bliidam III',
  'Bliilia',
  'Bliioid',
  'Bliirind Sigma',
  'Bliivania',
  'Blilis',
  'Blilore',
  'Blinus Ruins',
  'Blioid',
  'Blioid system',
  'Blioroid thule',
  'Blisuk',
  'Blitede 12',
  'Bliuium Prime',
  'Bliulon',
  'Bliury',
  'Blivania',
  'Blokagus',
  'Blokdam',
  'Blokdros',
  'Blokenerth',
  'Blokgus 12',
  'Blokilax',
  'Blokilore',
  'Blokisuk',
  'Blokjor',
  'Blokkon',
  'Bloklia',
  'Blokliv Prime',
  'Bloklon',
  'Blokolon-prism',
  'Bloktea cluster',
  'Bloktica-prism',
  'Blokubel',
  'Blokubula',
  'Blokury',
  'Catalia',
  'Catalore',
  'Cataran',
  'Catbel',
  'Catdros',
  'Catenliv',
  'Catenuria',
  'Catiketh',
  'Catirad',
  'Catjor Sigma',
  'Catkon',
  'Catliv',
  'Catosuk',
  'Catria cluster',
  'Catuserty',
  'Charbel',
  'Chardia III',
  'Charea',
  'Charellax',
  'Charenium',
  'Charenrind',
  'Charenuea Prime',
  'Chariketh',
  'Charjor cluster',
  'Charjor e4',
  'Charlia',
  'Charnus',
  'Charolon',
  'Charrind',
  'Charubula-X',
  'Charusroid',
  'Charveon',
  'Charveon-USR',
  'Cinasia cluster',
  'Cindia',
  'Cinea V',
  'Cinelea',
  'Cinellore',
  'Cinenlis',
  'Ciniliv',
  'Cinjor-USR',
  'Cinlia-USR',
  'Cinliv',
  'Cinliv Beta',
  'Cinlore',
  'Cinosia III',
  'Cinoury',
  'Cinru',
  'Cintica',
  'Cintos',
  'Cinuea system',
  'Claaea-prism',
  'Claajor',
  'Claanova',
  'Clabel',
  'Clabula-prism',
  'Claengua',
  'Claenkon',
  'Claenutea',
  'Claiea V',
  'Claierth 12',
  'Clairind',
  'Clalon',
  'Clalore',
  'Clalore-X',
  'Claoid homeworld',
  'Claokon',
  'Clarad',
  'Claran e3',
  'Claru',
  'Clatea',
  'Clatea system',
  'Claulia',
  'Clausvania',
  'Clautede',
  'Clazar',
  'Cliaea Prime',
  'Cliaium',
  'Cliaoid V',
  'Cliaroid',
  'Clieldam',
  'Clienulis',
  'Clienuzar',
  'Clierty',
  'Cligus',
  'Cliilax',
  'Cliium',
  'Cliiury',
  'Cliizar system',
  'Clilia',
  'Clioid cluster',
  'Cliria-X',
  'Cliuerty',
  'Cliuroid delta',
  'Cliuskon',
  'Clualia delta',
  'Clualis',
  'Clubula-prism',
  'Cludam',
  'Cludros',
  'Cluelzar e3',
  'Cluentea-RX',
  'Cluenulis',
  'Cluigua',
  'Clunova',
  'Cluogua',
  'Cluolore',
  'Cluoran',
  'Cluru',
  'Cluury',
  'Cluusdros',
  'Delavania',
  'Delbel e3',
  'Deldam',
  'Delelnus Prime',
  'Delennus',
  'Delidia',
  'Delirad',
  'Delium 12',
  'Dellia delta',
  'Delnus',
  'Deltos',
  'Delury',
  'Delveon Beta',
  'Delzar-RX',
  'Denaium e3',
  'Dendreus delta',
  'Dendros',
  'Deneldam',
  'Denelrind',
  'Denelsuk Sigma',
  'Denenuria',
  'Dengus Beta',
  'Denidam',
  'Denidreus Beta',
  'Denidros Beta',
  'Denilis',
  'Deninova',
  'Denirad V',
  'Denliv',
  'Denlore',
  'Dennova',
  'Dennova system',
  'Denobel-RX',
  'Denodam',
  'Densia',
  'Dentede Beta',
  'Denulia 12',
  'Dimalis',
  'Dimatede',
  'Dimdam',
  'Dimellon',
  'Dimenusuk',
  'Dimenvania Ruins',
  'Dimenveon',
  'Dimerty-X',
  'Dimnova',
  'Dimoid',
  'Dimoveon',
  'Dimria',
  'Dimuru',
  'Dimury',
  'Dimzar Prime',
  'Dinaerty Beta',
  'Dindam',
  'Dindam V',
  'Dinelgua',
  'Dinenulax e4',
  'Dinijor',
  'Dinilax',
  'Dinnus',
  'Dinru-prism',
  'Dinunus void',
  'Dinury',
  'Dinuserth-X',
  'Dolarind e3',
  'Dolbel',
  'Dolenudia',
  'Dolenutede',
  'Dolgus',
  'Dolidros-K2',
  'Doligua',
  'Dolium',
  'Doljor',
  'Dollon',
  'Doloerty',
  'Doloru',
  'Dolroid-helix',
  'Doltos',
  'Dolusea-RX',
  'Doluslis',
  'Dolvania',
  'Duvatede Prime',
  'Duvbel 12',
  'Duvbula V',
  'Duvdam void',
  'Duveldia e4',
  'Duvelgua',
  'Duveljor',
  'Duvenliv-prism',
  'Duverty',
  'Duvgua',
  'Duviium void',
  'Duvjor',
  'Duvlax',
  'Duvlis',
  'Duvliv',
  'Duvnus',
  'Duvroid',
  'Duvsuk',
  'Duvsuk-prism',
  'Duvudreus',
  'Duvutica Prime',
  'Dymbula e3',
  'Dymdreus',
  'Dymdros',
  'Dymea',
  'Dymea Ruins',
  'Dymea void',
  'Dymea-X',
  'Dymellore',
  'Dymelru void',
  'Dymelsuk',
  'Dymengua Prime',
  'Dymlax',
  'Dymugua',
  'Dymuoid',
  'Dymuru e3',
  'Dymusea Ruins',
  'Dymusveon',
  'Dymutede-K2',
  'Dymuzar Prime',
  'Dymzar',
  'Elaatede Prime',
  'Elabel',
  'Eladia Prime',
  'Eladros',
  'Elaelium',
  'Elaenbula',
  'Elaenuoid',
  'Elaerty-USR',
  'Elaium',
  'Elakon',
  'Elanova',
  'Elaorad',
  'Elaozar',
  'Elarad',
  'Elaran',
  'Elarind',
  'Elasia',
  'Elasuk thule',
  'Elatede',
  'Elatica',
  'Elaujor',
  'Elaulax',
  'Elaurind',
  'Eliatica',
  'Elibula',
  'Elidros',
  'Eliellax',
  'Elielroid Sigma',
  'Elienlore',
  'Eliidia-RX',
  'Eliodreus',
  'Elisia',
  'Elitica Ruins',
  'Eliustede',
  'Eliuszar',
  'Eloadia',
  'Elobula Beta',
  'Elodreus delta',
  'Elodreus III',
  'Elodreus-prism',
  'Eloelliv thule',
  'Eloenlon',
  'Elogua Beta',
  'Elojor',
  'Elojor V',
  'Elokon-K2',
  'Elolax Beta',
  'Elolax Prime',
  'Elolon',
  'Eloodreus',
  'Eloroid',
  'Eloru e4',
  'Eloudreus',
  'Esaran',
  'Eselea Beta',
  'Esenuliv e4',
  'Esenuury-K2',
  'Eserty-X',
  'Esgus',
  'Esidros',
  'Esilore-prism',
  'Eslon',
  'Eslore e3',
  'Esnova e4',
  'Esoid',
  'Esonova-RX',
  'Estos',
  'Etdia',
  'Etdreus V',
  'Eteljor homeworld',
  'Etenveon',
  'Etibula',
  'Etijor-K2',
  'Etlax Prime',
  'Etlia',
  'Etoid',
  'Etozar',
  'Etrind',
  'Etsia',
  'Etsuk',
  'Ettede',
  'Etubel',
  'Etudam',
  'Etury',
  'Foxarad',
  'Foxaveon',
  'Foxdia',
  'Foxelgus',
  'Foxenlax',
  'Foxensia',
  'Foxenudam',
  'Foxenutica Sigma',
  'Foxenuzar-RX',
  'Foxgus',
  'Foxium',
  'Foxjor thule',
  'Foxkon',
  'Foxkon cluster',
  'Foxlore',
  'Foxnova',
  'Foxrind',
  'Foxsia homeworld',
  'Foxtede',
  'Foxtica',
  'Foxusdam',
  'Foxusliv',
  'Frealon',
  'Freavania',
  'Freeldreus',
  'Freeldreus system',
  'Freentede void',
  'Freerty homeworld',
  'Fregua',
  'Freiran e4',
  'Frejor',
  'Frekon',
  'Frelax-helix',
  'Frelis-helix',
  'Frelore',
  'Frenova',
  'Frenus-prism',
  'Freodia V',
  'Freria',
  'Fretica V',
  'Frevania',
  'Frezar',
  'Galacalore',
  'Galacelrad',
  'Galacelru',
  'Galaceltica Ruins',
  'Galacenerty',
  'Galacenlore-K2',
  'Galacensuk-RX',
  'Galacentea',
  'Galacenudam III',
  'Galacenujor-X',
  'Galacenulon',
  'Galacierth',
  'Galacirad',
  'Galacium',
  'Galacium-prism',
  'Galackon 12',
  'Galaclon',
  'Galaclore system',
  'Galacobel',
  'Galacoerth',
  'Galacogua',
  'Galacoid',
  'Galaconus void',
  'Galacran-X',
  'Galacria Sigma',
  'Galacsuk',
  'Galactea-X',
  'Galactede',
  'Galactede e3',
  'Galacusgua',
  'Galacusuk',
  'Galaczar',
  'Galbel Beta',
  'Galeltica',
  'Galenran',
  'Galidreus 12',
  'Galidreus-RX',
  'Galliv',
  'Galnus',
  'Galobel',
  'Galria',
  'Galusbula',
  'Galvania',
  'Galvania homeworld',
  'Glakanova 12',
  'Glakdros',
  'Glakea',
  'Glakelketh',
  'Glakelria e4',
  'Glakennus',
  'Glakerth',
  'Glakgus',
  'Glakigua',
  'Glakigus',
  'Glakiria Ruins',
  'Glakisuk',
  'Glakjor',
  'Glakkon-K2',
  'Glaklax',
  'Glaktos',
  'Glakuketh-helix',
  'Glakuran',
  'Glakuserth',
  'Glakvania',
  'Japaium',
  'Japalon',
  'Japdreus V',
  'Japelium',
  'Japenrad system',
  'Japenuoid-K2',
  'Japenusuk',
  'Japerth',
  'Japerty',
  'Japidros',
  'Japigua',
  'Japkon V',
  'Japkon-USR',
  'Japlon',
  'Japnova',
  'Japru cluster',
  'Japtos',
  'Japtos-K2',
  'Jasaea homeworld',
  'Jasarind',
  'Jasdia',
  'Jaselrind',
  'Jaselrind-RX',
  'Jaseltea',
  'Jasengua',
  'Jasenubel',
  'Jasenulis',
  'Jasenury e4',
  'Jasenutea e4',
  'Jaserty',
  'Jasidreus',
  'Jasium',
  'Jasiveon Ruins',
  'Jaslis',
  'Jasliv Ruins',
  'Jasoid',
  'Jasran',
  'Jastede',
  'Jastede e4',
  'Jasuserth',
  'Jasusgua',
  'Jasuzar',
  'Jeldam e3',
  'Jeldia-prism',
  'Jeldreus',
  'Jeleltede',
  'Jelentede',
  'Jelenukon',
  'Jelenuroid Prime',
  'Jelenusia-X',
  'Jelerty Sigma',
  'Jeligua',
  'Jelinova',
  'Jeliria',
  'Jelolon',
  'Jelran',
  'Jelrind',
  'Jelroid',
  'Jelsuk',
  'Jeltos delta',
  'Jelury',
  'Jelzar',
  'Jesaea',
  'Jesdam',
  'Jesdia-K2',
  'Jesdreus',
  'Jesenerty cluster',
  'Jesenuea',
  'Jesenujor void',
  'Jesenunova thule',
  'Jeserth-prism',
  'Jeslax',
  'Jeslia',
  'Jeslis',
  'Jeslon',
  'Jeslon Beta',
  'Jesnova homeworld',
  'Jesnus III',
  'Jesoid Prime',
  'Jesokon-prism',
  'Jesolia',
  'Jesroid void',
  'Jesru',
  'Jestea',
  'Jestede',
  'Jestede-USR',
  'Jestica',
  'Jestos',
  'Jesusdros',
  'Jesusrad',
  'Jesusria',
  'Jesutede',
  'Jetaury',
  'Jetdia',
  'Jetdros delta',
  'Jetenlis',
  'Jetenuliv',
  'Jetenuliv e3',
  'Jetijor',
  'Jetilon',
  'Jetiroid III',
  'Jetitea Ruins',
  'Jetjor cluster',
  'Jetliv homeworld',
  'Jetlore',
  'Jetnova-USR',
  'Jetolia',
  'Jetoran',
  'Jetotea',
  'Jetria',
  'Jetury',
  'Junadros',
  'Junasia',
  'Jundia V',
  'Junelsuk',
  'Junelzar',
  'Junenbula delta',
  'Junenudia',
  'Junenzar',
  'Junjor',
  'Junlore Prime',
  'Junnova',
  'Junnova thule',
  'Junnus',
  'Junodam Beta',
  'Junoru',
  'Junoveon-USR',
  'Junran',
  'Junubula',
  'Kaanaran delta',
  'Kaandreus',
  'Kaandros cluster',
  'Kaanellax void',
  'Kaanelrad',
  'Kaanenlon-prism',
  'Kaanenulore',
  'Kaanenusuk',
  'Kaanenuvania',
  'Kaangua',
  'Kaangus-USR',
  'Kaanikon',
  'Kaanirind',
  'Kaanlia',
  'Kaannova 12',
  'Kaanran Prime',
  'Kaanusdreus',
  'Kaanustea',
  'Kaanveon',
  'Kapeljor Prime',
  'Kaperty',
  'Kapiria',
  'Kaplax',
  'Kapodia',
  'Kapru',
  'Kaptede-helix',
  'Kapudam V',
  'Kapugus',
  'Kapusdam system',
  'Kapusdros',
  'Kapusjor',
  'Kapusrind',
  'Kapusveon',
  'Katdros',
  'Katelbula',
  'Kateljor-prism',
  'Kateloid',
  'Katenulax',
  'Katerty-USR',
  'Katiea',
  'Katiria system',
  'Katnova',
  'Katnus-X',
  'Katosuk',
  'Katugua Prime',
  'Katunova',
  'Katurad',
  'Katuskon',
  'Katuslon',
  'Katveon Prime',
  'Keragus',
  'Kerbula-RX',
  'Kerdam',
  'Kerenudreus-USR',
  'Kerenuveon Prime',
  'Keritos-prism',
  'Keriveon',
  'Kerlore',
  'Kerroid',
  'Kerusdros delta',
  'Kerustede',
  'Limaerty e4',
  'Limanus',
  'Limellax-X',
  'Limelury-RX',
  'Limendam',
  'Limendros',
  'Limerty',
  'Limlis',
  'Limliv system',
  'Limovania-K2',
  'Limria',
  'Limugus',
  'Limusdreus',
  'Limuslia',
  'Lynabula',
  'Lynaliv',
  'Lynbel Prime',
  'Lynenujor',
  'Lynenveon',
  'Lynilore',
  'Lynkon',
  'Lynlore-K2',
  'Lynoerth',
  'Lynolis',
  'Lynonus',
  'Lynosuk',
  'Lynrad',
  'Lynria Prime',
  'Lynrind-RX',
  'Lynsuk-X',
  'Lynusia cluster',
  'Lynusuk',
  'Manaria Prime',
  'Mandreus',
  'Mandreus void',
  'Maneldreus',
  'Manelnova',
  'Manelury',
  'Manennova',
  'Manenubel',
  'Manenujor Ruins',
  'Manerty-X',
  'Mangus',
  'Maniveon Ruins',
  'Mankon',
  'Manlia',
  'Manlon',
  'Manlore-USR',
  'Manolia thule',
  'Mantica-RX',
  'Manuserth',
  'Manussuk',
  'Manuvania',
  'Manvania V',
  'Metdros',
  'Metelliv',
  'Metenzar',
  'Meterth',
  'Meterth Prime',
  'Metkon Beta',
  'Metlax Prime',
  'Metnova',
  'Metoid',
  'Metolon',
  'Metsia',
  'Metunus homeworld',
  'Metusjor',
  'Metutede void',
  'Mudasuk-prism',
  'Mudbula',
  'Mudelerty',
  'Mudellis',
  'Mudenium system',
  'Mudenlax-prism',
  'Mudenliv-K2',
  'Mudenrad',
  'Mudentos Prime',
  'Mudenukon-RX',
  'Mudenulore',
  'Mudenusuk Prime',
  'Mudium',
  'Mudkon',
  'Mudliv V',
  'Mudogua',
  'Mudoid Sigma',
  'Mududreus',
  'Muduserth',
  'Muduserth e4',
  'Mulaium',
  'Mulaveon e4',
  'Muldros',
  'Mulea',
  'Mulelsuk',
  'Mulendam thule',
  'Mulenuru',
  'Mulerty',
  'Mulgus thule',
  'Mulliv',
  'Mulliv Sigma',
  'Mulnova',
  'Muloliv e4',
  'Muloru',
  'Mulran',
  'Mulru',
  'Mulsia',
  'Multea',
  'Mulury V',
  'Muluslis',
  'Mulusury',
  'Mulvania',
  'Mupadreus-USR',
  'Muparu',
  'Mupdros',
  'Mupelliv',
  'Mupenria Sigma',
  'Mupenugua',
  'Mupenutede system',
  'Mupium Prime',
  'Mupium-USR',
  'Muplia',
  'Muplore e3',
  'Mupoid',
  'Muptea-RX',
  'Muptede',
  'Mupuoid-USR',
  'Mupury',
  'Mupury-helix',
  'Mupusoid',
  'Mupustea',
  'Mupzar Ruins',
  'Nadanova',
  'Nadavania-RX',
  'Nadgua delta',
  'Nadgua-helix',
  'Nadigua',
  'Nadium',
  'Nadivania e3',
  'Nadjor Sigma',
  'Nadlon',
  'Nadlon V',
  'Nadtea cluster',
  'Nadtede',
  'Naduliv',
  'Naduserth Beta',
  'Naduslia',
  'Nadvania',
  'Nadvania-helix',
  'Namaroid void',
  'Namasia',
  'Nambel',
  'Nambel system',
  'Nameldreus thule',
  'Namendreus-prism',
  'Namenurad',
  'Namerty',
  'Namgus',
  'Namjor',
  'Namlia',
  'Namoea',
  'Namria Prime',
  'Namury',
  'Namussia Prime',
  'Namussia Ruins',
  'Namusveon',
  'Namvania',
  'Nimbula',
  'Nimentos Prime',
  'Nimenugua',
  'Nimenutede',
  'Nimenutede-RX',
  'Niminus',
  'Niminus Prime',
  'Nimium',
  'Nimlis-K2',
  'Nimlon-helix',
  'Nimoid-K2',
  'Nimolis',
  'Nimrind',
  'Nimsia Beta',
  'Nimtea homeworld',
  'Nimtos',
  'Nimtos-prism',
  'Nimvania Prime',
  'Nimveon V',
  'Noibel delta',
  'Noidreus',
  'Noielerty',
  'Noienketh',
  'Noienkon',
  'Noienrad',
  'Noienudam',
  'Noienuketh',
  'Noiium',
  'Noilax system',
  'Noilis-RX',
  'Noilon',
  'Noilon 12',
  'Noioveon',
  'Noiran',
  'Noiran cluster',
  'Noiria-RX',
  'Noiru Beta',
  'Noitea',
  'Noitede',
  'Noitica',
  'Noizar',
  'Nomaium',
  'Nombula',
  'Nomenulis',
  'Nomenuvania',
  'Nomenzar',
  'Nomerty',
  'Nomgus',
  'Nomitos',
  'Nomlore',
  'Nomnova',
  'Nomrad',
  'Nomroid',
  'Nomtica',
  'Nomtos',
  'Nomuium',
  'Nomusrind e4',
  'Nomusroid',
  'Novaerth cluster',
  'Novbula',
  'Novenlis',
  'Novenugus',
  'Novenusuk e3',
  'Novikon thule',
  'Novilax void',
  'Novium',
  'Novkon',
  'Novlax',
  'Novlore',
  'Novobel-K2',
  'Novoid',
  'Novoium',
  'Novolis',
  'Novrad e3',
  'Novran-K2',
  'Novria',
  'Novroid',
  'Novsuk Sigma',
  'Novunus',
  'Novusbula',
  'Novustica',
  'Novuzar Prime',
  'Nudbel',
  'Nuddam',
  'Nuddros-RX',
  'Nudenuea',
  'Nudenuketh Prime',
  'Nudenuroid',
  'Nudenveon',
  'Nuderty',
  'Nudilon cluster',
  'Nudlax',
  'Nudlia',
  'Nudliv 12',
  'Nudlon',
  'Nudtede e4',
  'Nududreus void',
  'Nudulia',
  'Nudustos-X',
  'Oldia',
  'Oldia-X',
  'Olelnova',
  'Olenuveon',
  'Olerty',
  'Olgua',
  'Olijor system',
  'Olilis',
  'Oljor thule',
  'Ollax',
  'Ollia',
  'Ollis void',
  'Olnova',
  'Olojor',
  'Oloketh',
  'Oloria',
  'Olru',
  'Olsuk III',
  'Oltica',
  'Olusdros cluster',
  'Olusium',
  'Oluszar',
  'Olvania',
  'Osatica',
  'Oselketh Prime',
  'Osennus Beta',
  'Osenuketh cluster',
  'Osenutede Ruins',
  'Osisia',
  'Osiveon-USR',
  'Oskon system',
  'Oslax',
  'Osliv',
  'Osnova',
  'Osodam void',
  'Osozar',
  'Osran',
  'Osria',
  'Osrind',
  'Osudreus e3',
  'Osury',
  'Osusliv',
  'Osusria Beta',
  'Paraea',
  'Paralis',
  'Paratos',
  'Pardreus',
  'Pardros',
  'Parinova',
  'Pariroid',
  'Pariury e3',
  'Parkon',
  'Parrad',
  'Parran',
  'Parroid',
  'Parsia',
  'Parulis III',
  'Peldreus',
  'Peleltea-USR',
  'Pelenunus homeworld',
  'Pelenuoid',
  'Pelgus',
  'Pelitica Prime',
  'Pellax Sigma',
  'Pelliv',
  'Peloea',
  'Pelroid system',
  'Pelugus Beta',
  'Pelusea',
  'Pelveon',
  'Pentaea III',
  'Pentavania',
  'Pentea',
  'Penteltede',
  'Pentengus',
  'Pentenlis',
  'Pentioid',
  'Pentium-USR',
  'Pentlore 12',
  'Pentoid',
  'Pentria thule',
  'Pentunus e3',
  'Pentusbel thule',
  'Pentveon',
  'Pentveon-helix',
  'Peradam',
  'Peralia Ruins',
  'Perbel',
  'Perbula',
  'Perdam',
  'Perdreus',
  'Perenoid',
  'Perenutede',
  'Pererth e3',
  'Pererty',
  'Periium',
  'Perium-prism',
  'Perlax Prime',
  'Perlis void',
  'Perlon',
  'Pernova',
  'Peroid',
  'Perokon',
  'Peroury 12',
  'Perrad',
  'Perran-helix',
  'Perrind',
  'Persia-X',
  'Pertos Prime',
  'Peruria-USR',
  'Peruru',
  'Perusgus Prime',
  'Perustos',
  'Perutica Beta',
  'Petaketh',
  'Petaliv',
  'Petaran',
  'Petdam',
  'Petea system',
  'Peteltede',
  'Petenria thule',
  'Petenujor',
  'Petenulore 12',
  'Petenunova',
  'Petenuvania',
  'Peterth e4',
  'Petgua',
  'Petierth',
  'Petitede Prime',
  'Petjor',
  'Petlia',
  'Petlore',
  'Petoerth',
  'Petoury',
  'Petran',
  'Petria',
  'Petru',
  'Pettea e3',
  'Pettede',
  'Pettos thule',
  'Petuerty',
  'Petulis',
  'Petuliv',
  'Petulore homeworld',
  'Petusdia',
  'Pexdia Ruins',
  'Pexeltos',
  'Pexerth',
  'Pexgua',
  'Pexierth',
  'Pexilon-prism',
  'Pexisuk',
  'Pexlore',
  'Pexlore-helix',
  'Pexnova',
  'Pexodia',
  'Pexoid V',
  'Pexoveon',
  'Pexrad',
  'Pexria Ruins',
  'Pexsia Ruins',
  'Pexsuk',
  'Pextica',
  'Pexuketh',
  'Pexurad',
  'Pexusketh',
  'Pexusuk',
  'Pexvania-K2',
  'Pezakon',
  'Pezbel',
  'Pezbula',
  'Pezdros Beta',
  'Pezenrind e3',
  'Pezenuveon',
  'Pezerth homeworld',
  'Pezerty cluster',
  'Pezikon cluster',
  'Pezitica',
  'Pezlax',
  'Pezlax Prime',
  'Pezliv-X',
  'Pezran V',
  'Pezru',
  'Peztea',
  'Peztica',
  'Pezurind',
  'Pezustos',
  'Pezutea-X',
  'Porea void',
  'Porenran',
  'Porerth Ruins',
  'Porirind cluster',
  'Pornus',
  'Porria',
  'Portos',
  'Porurad',
  'Poruria',
  'Porusbula',
  'Porusvania e4',
  'Porvania III',
  'Porveon Sigma',
  'Prosalis',
  'Prosarind',
  'Prosdreus',
  'Proselbula',
  'Prosellore-K2',
  'Proselru V',
  'Proseltea cluster',
  'Prosentica',
  'Prosenubel Prime',
  'Prosenulon',
  'Prosenurad Ruins',
  'Prosenvania Sigma',
  'Proserth',
  'Prosgua',
  'Prosium',
  'Prosiveon',
  'Proslis-X',
  'Prosliv Beta',
  'Prosliv-K2',
  'Proslore Beta',
  'Prosnova system',
  'Prosnus',
  'Prosran homeworld',
  'Prossuk',
  'Prosuium',
  'Prosulia',
  'Prosusgua III',
  'Prosvania',
  'Prosvania V',
  'Proszar Sigma',
  'Quagus',
  'Qudam',
  'Quea',
  'Quenlis Sigma',
  'Quenusia',
  'Quium Sigma',
  'Qujor',
  'Quketh',
  'Quliv',
  'Qulore',
  'Qurad system',
  'Quran',
  'Quroid',
  'Quukon 12',
  'Quvania delta',
  'Quzar',
  'Resaran',
  'Resdam',
  'Resdreus 12',
  'Reseltea',
  'Resenketh',
  'Resenlore',
  'Resenuveon Sigma',
  'Resenuzar void',
  'Reserth',
  'Reserth-USR',
  'Resgua',
  'Residreus-X',
  'Resitede e3',
  'Reslis-X',
  'Reslon Prime',
  'Resnova 12',
  'Resnus',
  'Resonova',
  'Resorad',
  'Resorad-prism',
  'Resotos',
  'Ressuk',
  'Restea',
  'Restos',
  'Resugus',
  'Resusdam',
  'Resuserth',
  'Resusketh',
  'Resusrad e3',
  'Reszar',
  'Rilagua',
  'Rilaroid',
  'Rilatea',
  'Rilea',
  'Rilelerth void',
  'Rilelnus',
  'Rilelveon thule',
  'Rilenroid-RX',
  'Rilgua',
  'Riliketh',
  'Rililore-helix',
  'Riljor',
  'Rilliv',
  'Rilnova',
  'Riloerth V',
  'Riloium Ruins',
  'Rilria',
  'Rilrind',
  'Riltos delta',
  'Rilustica homeworld',
  'Rivanus',
  'Rivaroid Ruins',
  'Rivelkon Prime',
  'Rivenium',
  'Rivenlia',
  'Rivenudreus V',
  'Rivenurind',
  'Rivgus',
  'Rivigua',
  'Rivizar',
  'Rivjor',
  'Rivjor e4',
  'Rivlax Prime',
  'Rivlia',
  'Rivlia e4',
  'Rivlon',
  'Rivlon-USR',
  'Rivnova',
  'Rivran homeworld',
  'Rivrind',
  'Rivru',
  'Rivugus',
  'Rivulore',
  'Rivuserty',
  'Rivussia',
  'Rizbel V',
  'Rizdam cluster',
  'Rizea delta',
  'Rizenea',
  'Rizenerth',
  'Rizenuveon',
  'Rizidreus-helix',
  'Rizilis',
  'Rizkon',
  'Riznova',
  'Riznus-RX',
  'Rizodia',
  'Rizodreus',
  'Rizoury-K2',
  'Rizria',
  'Rizrind',
  'Riztede',
  'Rizulia',
  'Rizuskon 12',
  'Rizusveon-prism',
  'Rizveon',
  'Rolatea homeworld',
  'Rolensia',
  'Rolenugus',
  'Rolenunova cluster',
  'Rolenusuk',
  'Rolerty thule',
  'Rolilon',
  'Rolisuk-USR',
  'Rolitica',
  'Roliveon',
  'Roljor',
  'Rolnus e3',
  'Rolrad',
  'Rolria',
  'Roludreus',
  'Rolulon',
  'Rolusroid 12',
  'Rolusru void',
  'Rolustica',
  'Rotadreus',
  'Rotasia',
  'Rotentede',
  'Rotenulax e3',
  'Rotenusia',
  'Rotenuzar',
  'Rotgua',
  'Rotkon e3',
  'Rotlax',
  'Rotliv',
  'Rototea',
  'Roturoid',
  'Rotury e4',
  'Rotusbel',
  'Rotuserth',
  'Rusendia',
  'Rusenea',
  'Rusenudros Ruins',
  'Rusidia',
  'Rusilax thule',
  'Rusinova',
  'Rusinova void',
  'Rusium 12',
  'Rusnova',
  'Rusoid',
  'Rusolax',
  'Rusolax-K2',
  'Rusran',
  'Rusrind',
  'Rustica',
  'Rusudreus',
  'Rususea Prime',
  'Rusussia system',
  'Rutaerth 12',
  'Rutbula thule',
  'Rutdam void',
  'Rutdia Beta',
  'Rutensia-USR',
  'Rutenubula thule',
  'Ruterty',
  'Rutgua',
  'Rutgua delta',
  'Rutlis',
  'Rutogua',
  'Rutoid',
  'Ruttea',
  'Rutuerth-X',
  'Rutunova',
  'Rutusria',
  'Sionabel Prime',
  'Sionelbel thule',
  'Sioneldia',
  'Sionenium',
  'Siongus III',
  'Sionkon',
  'Sionlax',
  'Sionlax-helix',
  'Sionlia 12',
  'Sionlis homeworld',
  'Sionliv',
  'Sionnus system',
  'Sionoid',
  'Sionoran',
  'Sionru thule',
  'Sionurad',
  'Sionusea',
  'Sionussia',
  'Sionuveon',
  'Sionveon',
  'Sizatica',
  'Sizaveon III',
  'Sizdam',
  'Sizdros Ruins',
  'Sizeljor Beta',
  'Sizenliv',
  'Sizenzar',
  'Sizlia',
  'Sizsia',
  'Siztica',
  'Sizunus',
  'Sizuskon delta',
  'Sizveon delta',
  'Thonalia',
  'Thonarind',
  'Thonbula-helix',
  'Thoneldreus e4',
  'Thonenulon',
  'Thonenusuk',
  'Thoniium',
  'Thoninova',
  'Thonketh',
  'Thonlon',
  'Thonnova',
  'Thonotica',
  'Thonria 12',
  'Thonuserth',
  'Thonzar',
  'Thoraliv e4',
  'Thorbel',
  'Thorbula',
  'Thordros',
  'Thorelium',
  'Thorenrind',
  'Thorerth homeworld',
  'Thorerty',
  'Thorgua',
  'Thoribula-prism',
  'Thorilon',
  'Thoriveon Prime',
  'Thorlia',
  'Thorlis',
  'Thorliv e3',
  'Thornus',
  'Thoroketh-X',
  'Thorveon',
  'Thuaria',
  'Thubula',
  'Thudia',
  'Thudia void',
  'Thuelbel',
  'Thuelrad',
  'Thuenran-X',
  'Thugus void',
  'Thukon Beta',
  'Thuliv',
  'Thulon',
  'Thulore Prime',
  'Thuotica',
  'Thuru',
  'Thutos',
  'Thuusran-USR',
  'Thuvania',
  'Thuveon-helix',
  'Thuzar',
  'Timaliv-prism',
  'Timaroid',
  'Timbel',
  'Timelury system',
  'Timendia',
  'Timenkon',
  'Timinus-helix',
  'Timoid',
  'Timoid Ruins',
  'Timroid Sigma',
  'Timtica',
  'Timury',
  'Timvania',
  'Trisagua void',
  'Trisaury Prime',
  'Trisbula-helix',
  'Trisdros',
  'Triselria',
  'Trisenudia',
  'Trisenuury',
  'Trisgua',
  'Trisijor',
  'Trisikon delta',
  'Trisinova',
  'Triskon cluster',
  'Trisliv e4',
  'Trisokon thule',
  'Trisoru',
  'Trisotica',
  'Trisrad',
  'Trisrad delta',
  'Trisran',
  'Trisria',
  'Trisru',
  'Trissuk delta',
  'Tristica',
  'Trisulon',
  'Trisurind',
  'Trisury',
  'Trisusketh',
  'Triszar',
  'Tromalis',
  'Tromarind',
  'Tromeloid',
  'Tromelsuk',
  'Tromennova Prime',
  'Tromenuium',
  'Tromenuvania',
  'Tromium-X',
  'Tromlon',
  'Tromria',
  'Tromrind',
  'Tromsuk',
  'Tromtea',
  'Tromury homeworld',
  'Tromussia-helix',
  'Trosaketh void',
  'Trosdia',
  'Trosenkon-X',
  'Trosenulore',
  'Trosenutos-X',
  'Trosgus',
  'Trosidia-prism',
  'Trosigus',
  'Trosium',
  'Troskon',
  'Troslis 12',
  'Trosliv Sigma',
  'Trosobula V',
  'Trosodreus delta',
  'Trosolia',
  'Trosoran',
  'Trosrind-K2',
  'Trostea',
  'Trosveon',
  'Tunagus',
  'Tunaoid delta',
  'Tunasuk e4',
  'Tunbel',
  'Tunbula',
  'Tunelbula-K2',
  'Tunelkon',
  'Tunenroid',
  'Tunenulax',
  'Tunnus void',
  'Tunoid',
  'Tunoru',
  'Tunrad 12',
  'Tunsuk',
  'Tuntos',
  'Tunury',
  'Tunzar',
  'Vicdam',
  'Viceldros thule',
  'Vicellax',
  'Vicelnova',
  'Vicentica',
  'Vicenulore',
  'Vicgus',
  'Viciketh',
  'Vicjor e4',
  'Vickon thule',
  'Viclax',
  'Viclis',
  'Viclon',
  'Viclore',
  'Vicrad',
  'Vicru',
  'Vicsia',
  'Vicsuk',
  'Victica',
  'Victos-USR',
  'Vicuserty V',
  'Vicussia',
  'Vicvania-RX',
  'Vicveon Beta',
  'Xamaketh',
  'Xamdia',
  'Xamelgua',
  'Xameltos',
  'Xamenbula V',
  'Xamenjor',
  'Xamenulia',
  'Xamium',
  'Xamium 12',
  'Xamlore',
  'Xamodam',
  'Xamolax',
  'Xamorind-USR',
  'Xamran',
  'Xamria',
  'Xamrind cluster',
  'Xamsia',
  'Xamustede-K2',
  'Xamusuk cluster',
  'Xamuzar',
  'Xanarad',
  'Xanbel',
  'Xanenubel',
  'Xanenugus',
  'Xanenuzar',
  'Xanenveon',
  'Xangua V',
  'Xanidros',
  'Xanigus',
  'Xanitea III',
  'Xanizar-RX',
  'Xanlis-prism',
  'Xanlore',
  'Xannova',
  'Xanrad-prism',
  'Xanria',
  'Xansia e3',
  'Xanuea',
  'Xanury',
  'Xanusdreus',
  'Xonalore',
  'Xondreus',
  'Xonelnus',
  'Xonenugua',
  'Xonenunus',
  'Xonerth',
  'Xoniium homeworld',
  'Xonliv',
  'Xonoid delta',
  'Xononus Prime',
  'Xonoroid',
  'Xonotea',
  'Xonroid',
  'Xonroid-X',
  'Xontea',
  'Xonury 12',
  'Xonuskon',
  'Xonvania Prime',
  'Zembel',
  'Zembula',
  'Zemenkon',
  'Zementede',
  'Zemenuea system',
  'Zemenulia',
  'Zemenulia void',
  'Zemenveon Beta',
  'Zemirind',
  'Zemitea void',
  'Zemitica system',
  'Zemium',
  'Zemlia',
  'Zemliv',
  'Zemoid thule',
  'Zemoliv Sigma',
  'Zemran',
  'Zemtos-RX',
  'Zemudam',
  'Zemury III',
  'Zemusdreus',
  'Zenalon',
  'Zenalore',
  'Zendam',
  'Zendia',
  'Zeneldia',
  'Zenenrind',
  'Zenenulon',
  'Zenenusuk',
  'Zenenzar',
  'Zengua',
  'Zengus',
  'Zenierth',
  'Zennus Prime',
  'Zenotos',
  'Zenrad',
  'Zenria',
  'Zenrind-K2',
  'Zenroid system',
  'Zensia void',
  'Zentica',
  'Zenubel',
  'Zenunus',
  'Zenury-RX',
  'Zenveon',
  'Zinengua e4',
  'Zinenrind-X',
  'Zinenru-K2',
  'Zinenuvania',
  'Zinjor',
  'Zinketh',
  'Zinoru-helix',
  'Zinsuk',
  'Zintede-RX',
  'Zinuria',
  'Zinusnus',
  'Zionaerty 12',
  'Zionbula system',
  'Ziondia',
  'Ziondros',
  'Zionellax-K2',
  'Zionenrad e4',
  'Zionenria thule',
  'Zionenudia',
  'Ziongua',
  'Zioninus-RX',
  'Zionnova V',
  'Zionodros',
  'Zionolon',
  'Zionran Sigma',
  'Ziontede',
  'Zionulax-USR',
  'Zionury',
  'Zionury-prism',
  'Zionustede void',
  'Zionvania delta',
  'Zionzar',
  'Zuladros',
  'Zuldam Beta',
  'Zuldia',
  'Zulenliv',
  'Zulerth-X',
  'Zuliroid',
  'Zulium',
  'Zullon',
  'Zuloid cluster',
  'Zulrad',
  'Zulrad-RX',
  'Zulria',
  'Zulrind',
  'Zultea',
  'Zuluran-RX',
  'Zulusia e3',
  'Zulusia V',
  'Zulusveon',
  'Zulzar',
  'Zyndia Ruins',
  'Zyndreus',
  'Zyndreus thule',
  'Zynentica',
  'Zynenulon',
  'Zynerty',
  'Zynium',
  'Zynodros',
  'Zynrind V',
  'Zynuria-X',
  'Zynuslia',
  'Zynuury',
  'Zynveon',
]
